"use client"
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Nathan Sioui (https://sketchfab.com/NathanSioui)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/old-television-86c2567eddd0460cb3127be05cc66450
title: Old Television
*/

import React, { useRef } from "react"
import { useGLTF } from "@react-three/drei"
import { GLTF } from "three/examples/jsm/loaders/GLTFLoader"

type GLTFResult = GLTF & {
    nodes: {
        Object_2: THREE.Mesh
    }
    materials: {
        ["TV_Low_initialShadingGroup"]: THREE.MeshStandardMaterial
    }
}

export function Television(props: any) {
    const { nodes, materials } = useGLTF(
        "/assets/models/old_television_high.glb"
    ) as unknown as GLTFResult
    return (
        <group {...props} dispose={null}>
            <group rotation={[-Math.PI / 2, 0, 0]}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_2.geometry}
                    material={materials.TV_Low_initialShadingGroup}
                />
            </group>
        </group>
    )
}

useGLTF.preload("/old_television_high.glb")
